Make tbl2asn never expire

diff --git a/prokka/v1.14/Dockerfile b/prokka/v1.14/Dockerfile
--- a/prokka/v1.14/Dockerfile
+++ b/prokka/v1.14/Dockerfile
@@ -1,7 +1,11 @@
 FROM debian:buster-slim
 
 RUN apt-get update && \
-    apt-get install -y bioperl && \
+    apt-get install -y \
+      bioperl \
+      libfaketime \
+      libidn11 \
+    && \
     rm -rf /var/lib/apt
 
 LABEL software.version="v1.14.0"
@@ -10,7 +14,13 @@ COPY --from=quay.io/refgenomics/aragorn:1.2.38 /usr/local/bin/aragorn /usr/local
 
 COPY --from=quay.io/refgenomics/prodigal:2.6.3 /usr/local/bin/prodigal /usr/local/bin/
 
-COPY --from=quay.io/refgenomics/tbl2asn:latest /usr/local/bin/tbl2asn /usr/local/bin/
+COPY --from=quay.io/refgenomics/tbl2asn:latest /usr/local/bin/tbl2asn /usr/local/bin/real-tbl2asn
+
+# prevent tbl2asn from expiring
+# (see https://github.com/audy/tbl2asn-forever)
+RUN echo 'set -euo pipefail LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1 FAKETIME="2019-01-01 00:00:01" /usr/bin/real-tbl2asn $*' \
+  > /usr/local/bin/tbl2asn \
+  && chmod +x /usr/local/bin/tbl2asn
 
 COPY --from=quay.io/refgenomics/hmmer:3.2.1 /usr/local/bin/* /usr/local/bin/
 
